baseURL = "https://mebucca.github.io/"
languageCode = "en-us"
title = "Mauricio Bucca"
theme = "hugo-theme-console"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML (for photo, etc.)

[params]
  description = "Inequality · Social Mobility · Computational Social Science"
  footer = "© 2025 Mauricio Bucca · Pontificia Universidad Católica de Chile"

  # ✅ Homepage content (instead of the demo “Console is a minimal…”)
  home = """
# Mauricio Bucca
Assistant Professor of Sociology, Pontificia Universidad Católica de Chile

_Inequality · Social Mobility · Computational Social Science_

<p align="center">
  <img src="static/images/me.jpg" alt="Mauricio Bucca" style="width: 260px; border-radius: 50%;"/>
</p>

## Bio
I’m an Assistant Professor in Sociology at the Pontificia Universidad Católica de Chile. Previously, I was a Max Weber Postdoctoral Fellow at the European University Institute and earned a Ph.D. in Sociology at Cornell University.

I study labor market inequalities, intergenerational mobility, and beliefs about inequality using statistical modeling, causal inference, experiments, and computational methods.

## Research & Methods (at a glance)
- Structural inequality: intergenerational mobility, labor-market gaps, educational assortative mating
- Cultural facets: beliefs about inequality and fairness
- Methods: Bayesian models (structured dispersion), log-linear models with Lasso, Monte Carlo simulation, large-scale online experiments
"""

# LEFT → RIGHT order for navigation menu
[[params.navlinks]]
  name = "About"
  url  = "/"

[[params.navlinks]]
  name = "Publications"
  url  = "/publications/"

[[params.navlinks]]
  name = "Ongoing Work"
  url  = "/ongoing-work/"

[[params.navlinks]]
  name = "Teaching"
  url  = "/teaching/"
